/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package responsi2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Prasasti
 */
public class perpustakaan extends javax.swing.JFrame {
    DefaultTableModel model;
    String tabel_klik="";
    Connection conn = KoneksiDB.getKoneksi();

    /**
     * Creates new form perpustakaan
     */
    public perpustakaan() {
        initComponents();
        model=(DefaultTableModel)tbDatabase.getModel();
        this.loadDataToTable();
    }
    
    public void loadDataToTable(){
        DefaultTableModel dm = (DefaultTableModel)tbDatabase.getModel();
        while (dm.getRowCount() > 0){
            dm.removeRow(0);
        }
        
        try {
            Connection conn=KoneksiDB.getKoneksi();
            Statement s = conn.createStatement();
            String query ="SELECT * FROM tb_buku";
            ResultSet result = s.executeQuery(query);
            
            while(result.next()){
                Object [] obj = new Object [4];
                obj[0] = result.getString("id_buku");
                obj[1] = result.getString("judul");
                obj[2] = result.getString("penulis");
                obj[3] = result.getInt("tahun");
                
                model.addRow(obj);
            }
            result.close();
            s.close();
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        finally{
            tabel_klik = "";
        }
    }
 
    public void printDataBuku() throws TahunTerbitHarusAngka, TahunTerbitHarus4Digit{
        int tahun;
        
        try {
            tahun = Integer.parseInt(txtTahun.getText());
        } catch (NumberFormatException e) {
            throw new TahunTerbitHarusAngka();
        }
        
        tahun = txtTahun.getText().length();
        if (tahun < 4 || tahun > 4){
            throw new TahunTerbitHarus4Digit();
        }
        
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtJudul = new javax.swing.JTextField();
        txtPenulis = new javax.swing.JTextField();
        txtTahun = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDatabase = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Data Buku");

        jLabel2.setText("ID Buku");

        jLabel3.setText("Judul Buku");

        jLabel4.setText("Penulis");

        jLabel5.setText("Tahun Terbit");

        txtID.setEditable(false);

        btnSimpan.setText("SIMPAN");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });

        btnUbah.setText("UBAH");
        btnUbah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUbahMouseClicked(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        tbDatabase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Buku", "Judul Buku", "Penulis", "Tahun Terbit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbDatabase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDatabaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDatabase);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(178, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelete)
                        .addGap(30, 30, 30))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
        
        try {
            this.printDataBuku();
        } catch (TahunTerbitHarusAngka e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (TahunTerbitHarus4Digit e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        try{
            Connection conn = KoneksiDB.getKoneksi();
            String query = "INSERT INTO tb_buku" + "(judul,penulis,tahun)" + "VALUE(?,?,?)";
            PreparedStatement p = conn.prepareStatement(query);
            
            p.setString(1, txtJudul.getText());
            p.setString(2, txtPenulis.getText());
            p.setString(3, txtTahun.getText());
            
            int rowsInserted = p.executeUpdate();
            if(rowsInserted > 0){
                JOptionPane.showMessageDialog(this, "Data Buku Berhasil Disimpan", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            p.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Buku Gagal Disimpan", "Error", JOptionPane.ERROR_MESSAGE);
        }
        finally{
            this.loadDataToTable();
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void btnUbahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUbahMouseClicked
        // TODO add your handling code here:
        try {
            Connection conn = KoneksiDB.getKoneksi();
            String query = "UPDATE tb_buku SET judul=?,penulis=?,tahun=? WHERE id_buku=?";
            PreparedStatement p = conn.prepareStatement(query);
            
            p.setString(1, txtJudul.getText());
            p.setString(2, txtPenulis.getText());
            p.setString(3, txtTahun.getText());
            p.setString(4, txtID.getText());
            
            int rowsUpdate = p.executeUpdate();
            if(rowsUpdate > 0){
                JOptionPane.showMessageDialog(this, "Data Buku Berhasil diUpdate", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
            p.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Data Buku Gagal diUpdate", "Error", JOptionPane.ERROR_MESSAGE);
        }
        finally{
            this.loadDataToTable();
        }
    }//GEN-LAST:event_btnUbahMouseClicked

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        if(!tabel_klik.equals("")){
            try {
                Connection conn = KoneksiDB.getKoneksi();
                String query = "DELETE FROM tb_buku WHERE id_buku=?";
                PreparedStatement p = conn.prepareStatement(query);
                p.setString(1, txtID.getText());
                int rowsDeleted = p.executeUpdate();
                if(rowsDeleted > 0){
                    JOptionPane.showMessageDialog(this, "Data Buku Berhasil diHapus", "Success", JOptionPane.INFORMATION_MESSAGE);
                }
                p.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Data Buku Berhasil diHapus", "Error", JOptionPane.ERROR_MESSAGE);
            }
            finally{
                this.loadDataToTable();
            }
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void tbDatabaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDatabaseMouseClicked
        // TODO add your handling code here:
        int row = tbDatabase.getSelectedRow();
        tabel_klik = (tbDatabase.getModel().getValueAt(row, 3).toString());
        txtID.setText(tabel_klik);
        
        txtID.setText(tbDatabase.getModel().getValueAt(row, 0).toString());
        txtJudul.setText(tbDatabase.getModel().getValueAt(row, 1).toString());
        txtPenulis.setText(tbDatabase.getModel().getValueAt(row, 2).toString());
        txtTahun.setText(tbDatabase.getModel().getValueAt(row, 3).toString());
    }//GEN-LAST:event_tbDatabaseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perpustakaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDatabase;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtPenulis;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
